version: "3"

services:

  application:

    image: docker-api-demo
    container_name: docker-api-demo-container

    environment:
      - "SPRING_PROFILES_ACTIVE=dev"

    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
      - "8085:8085"


  pactbroker:

    image: dius/pact-broker
    container_name: pact-broker-container
    ports:
      - "8090:80"
    environment:
      PACT_BROKER_DATABASE_ADAPTER: sqlite
      PACT_BROKER_DATABASE_NAME: pact_broker.sqlite